### ISSUE TITLE
Intermittent immediate disconnect upon connecting wallet

### ISSUE THREAD

**Issue by deHB6** [cawabunga/headless-web3-provider#16]
@cawabunga Occasionally, especially at the beginning of e2e tests run with playwright and latest version of headless-web3-provider, when we go to connect wallet with rainbowkit, the wallet connects and then immediately disconnects.  Manually clicking connect again in the headed window throws this error.  Refreshing browser solves, but we don't do this in the CI and are hoping to avoid needing hacky workarounds.

ConnectedError: Connector already connected
    at connect (chunk-TSH6VVF4.js:654:1)
    at Object.mutationFn (index.js:722:17)
    at Object.fn (mutation.mjs:87:1)
    at run (retryer.mjs:101:1)
    at createRetryer (retryer.mjs:149:1)
    at executeMutation (mutation.mjs:81:35)
    at Mutation.execute (mutation.mjs:138:1)
    at async connectWallet (chunk-KM5A65HC.js:13787:1)
console.er

<img width="1523" alt="image" src="https://github.com/cawabunga/headless-web3-provider/assets/129817868/725072ed-9f3d-489c-bb56-28c003e58328">

**Comment by cawabunga** [comment]
Not sure if it is still relevant, but could you create a reproduction of it in the new repository, so I could examine it?

**Comment by deHB6** [comment]
All good, i have resolved by adding a 3 second wait between prompting the connection and approving it

**Comment by cawabunga** [comment]
Can you share a website you are testing? I will try to reproduce and find root cause.
