### ISSUE TITLE
Request for eth_signTypedData for EIP712 signatures

### ISSUE THREAD

**Issue by deHB6** [cawabunga/headless-web3-provider#2]
The application I am working on uses signatures heavily.  We have had great success with this package so far integrated with playwright but noticed it does not support `eth_signTypedData`.  Wanted to see what you thought about adding it? Doesn't look like it will be too much and perhaps something we could try to PR? @cawabunga @romanlv

**Comment by cawabunga** [comment]
Hey @deHB6, could you say what version of "eth_signTypedData" you rely on? There are v1, v3 and v4 versions, although v1 and v3 are deprecated. Here is a link, that helps clarify things https://docs.metamask.io/wallet/concepts/signing-methods/#eth_signtypeddata_v1-and-eth_signtypeddata_v3

**Comment by cawabunga** [comment]
I have added all sign_typed methods https://github.com/cawabunga/headless-web3-provider/pull/3 and published new version on [NPM](https://www.npmjs.com/package/headless-web3-provider/v/0.1.14).

**Comment by deHB6** [comment]
Thank you so much!!
