### ISSUE TITLE
Missing `dist` directory in `0.2.0`

### ISSUE THREAD

**Issue by daenamkim** [cawabunga/headless-web3-provider#6]
**v0.2.0**

<img width="1164" alt="image" src="https://github.com/cawabunga/headless-web3-provider/assets/16159767/3e939fad-e11a-42a9-ab21-2360efeecc28">

<img width="347" alt="image" src="https://github.com/cawabunga/headless-web3-provider/assets/16159767/7356c31a-7cb7-4487-b53d-47571883a9b3">

**v0.1.14**

<img width="471" alt="Screenshot 2023-08-21 at 12 31 54" src="https://github.com/cawabunga/headless-web3-provider/assets/16159767/9ba5388b-85ec-4e3c-ac33-235f14df3a43">

@cawabunga If you don't mind can you build and re-publish this?

**Comment by cawabunga** [comment]
Thanks for reporting, I should have checked it. That's weird. I republished as `0.2.1`.
