### ISSUE TITLE
`RequestPermissions` is missing in 0.2.1

### ISSUE THREAD

**Issue by daenamkim** [cawabunga/headless-web3-provider#8]
@cawabunga Hi, I have no idea why `RequestPermissions` is missing on my end but I found it is (probably) missing in only npm package. Can you have a look and republish if you don't mind?

_Installed from npm_
<img width="1153" alt="Screenshot 2023-08-24 at 18 27 28" src="https://github.com/cawabunga/headless-web3-provider/assets/16159767/3540c3c0-87f6-46d1-9d50-6edfa7e7fb6d">

_Local build_
<img width="1515" alt="Screenshot 2023-08-24 at 18 28 57" src="https://github.com/cawabunga/headless-web3-provider/assets/16159767/b5df581f-059c-450f-a0b6-101c46507d1c">

**Comment by cawabunga** [comment]
Thanks for reporting. I suspect that parcel messes up the output. Now parcel cache is purged before build process. https://github.com/cawabunga/headless-web3-provider/commit/7bb60c8d8972015227ba3719c15ac2cb2c279f2e 

I released `0.2.2` that addresses this issue.
